name: Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


env:
  DEVOPS_DIR: python_project


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          pyinstaller -F main.py

      - name: Show files
        run: |
          cd dict
          pwd
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: ./dict/main.exe
