name: Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    env:
      EXE_ARTIFACTS_DIR: '/home/runner/work/DevOps_first_lab/DevOps_first_lab/dist/'
      LINK: 'https://www.youtube.com/watch?v=vx2u5uUu3DE'
      DOCKER_USERNAME: 'forestwildrabbit'
      DOCKER_TAG: 'forestwildrabbit/devops_lab:v1'

    runs-on: ubuntu-latest

    steps:
      - name: checkout repository content
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build an executable
        run: |
          pyinstaller -F main.py
          

      - name: Run exe
        run: |
          cd dist
          chmod +x main
          ./main ${{env.LINK}}

      - name: Upload a Build Artifact executable
        uses: actions/upload-artifact@v3
        with:
          name: executable-artifact
          path: ${{env.EXE_ARTIFACTS_DIR}}
          retention-days: 1

      - name: Check audio
        run: |
          cd dist
          cd audiofiles
          ls -lha

      - name: Build and Push a docker image
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{env.DOCKER_USERNAME}}" --password-stdin
          docker image build -t "${{env.DOCKER_TAG}}" .
          docker push "${{env.DOCKER_TAG}}"

      

      



